#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

until cd /app
do
    echo "Waiting for server volume..."
done

/wait-for-schema

python manage.py collectstatic --noinput
python manage.py compilemessages

#gunicorn config.wsgi --bind 0.0.0.0:8000 --workers 1
echo "Starting daphne!"
exec daphne config.asgi:application -b 0.0.0.0 -p 8000
