#!/bin/sh
set -o errexit
set -o pipefail
set -o nounset

/wait-for-schema

echo "[dev] Collecting static files..."
python manage.py collectstatic --noinput --clear

echo "[dev] Starting dev server (auto-reload on code changes)..."
uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload
