#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

/wait-for-schema

echo "[dev] Starting Celery beat..."
exec celery -A config.celery_app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
