#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

/wait-for-schema

rm -f './celerybeat.pid'
exec celery -A config.celery_app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
