#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset
/wait-for-schema

echo "Starting uvicorn (ASGI server with WebSocket support and auto-reload)..."
exec uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload
